subject=["c","c++","python","java","php"]
print(subject)
print(subject[1])
print(subject[1:])
print(subject[-1])
print("c" in subject)
print("html" in subject)
print(subject[2:])
print(subject+["saif",23])
print(subject*3)
print(subject+["saif",23])
print(len(subject))
subject.append("toc")
print(subject)
subject.append("saif")
print(subject)
subject.append("ibadullah")
print(subject)
subject.insert(2,"saif")
print(subject)
subject.remove("ibadullah")
print(subject)
subject.sort()
print(subject)
subject.append("a")
print(subject)
subject.sort()
print(subject)
subject.pop()
print(subject)
subject.clear()
print(subject)
subject2=subject.copy()
print(subject2)
num=list(range(20))
print(num)
num=list(range(2,10))
print(num)
num=list(range(2,101,2))
print(num)





